package models;

import java.util.Date;

// This file was generated by common.basic.genModels.Main.
// DO NOT EDIT THIS FILE MANUALLY.
@SuppressWarnings("UnusedDeclaration")
public class AccountDevice extends ModelAutoIncrement {
    public Account account;
    public Device device;
}
