package models;

import java.util.Date;

// This file was generated by common.basic.genModels.Main.
// DO NOT EDIT THIS FILE MANUALLY.
@SuppressWarnings("UnusedDeclaration")
public class Account extends ModelUuid {
    public String email;
    public String salt;
    public String password;
    public boolean isEmailVerified;
    public Date dateEmailVerified;
    public String emailVerificationCode;
    public boolean isLeaved;
    public Date dateLeaved;
    public String leavedReason;
    public Date dateLastLoggedIn;
    public AttachmentAccountProfile attachmentAccountProfile;
}
