package models;

import java.util.Date;

// This file was generated by common.basic.genModels.Main.
// DO NOT EDIT THIS FILE MANUALLY.
@SuppressWarnings("UnusedDeclaration")
public abstract class Attachment extends ModelAutoIncrement {
    public String fileName;
    public long fileLength;
    public long countDownload;
}
