package models;

import java.util.Date;

// This file was generated by common.basic.genModels.Main.
// DO NOT EDIT THIS FILE MANUALLY.
@SuppressWarnings("UnusedDeclaration")
public abstract class ModelBase {
    public Date dateCreated = new Date();
    public Date dateModified = new Date();
}

