package models;

import java.util.Date;

// This file was generated by common.basic.genModels.Main.
// DO NOT EDIT THIS FILE MANUALLY.
@SuppressWarnings("UnusedDeclaration")
public class Notice extends ModelAutoIncrement {
    public String ticker;
    public String contentTitle;
    public String contentText;
    public String url;
}
